#!/usr/bin/env python3
import subprocess
import sys
import os
import json

path = ""
output = ""
if len(sys.argv) > 2:
    path = os.path.expanduser(sys.argv.pop(1))

    output = ""
    if sys.argv[1] == "cd":
        newpath = ""
        if len(sys.argv) == 2:
            newpath = os.path.expanduser("~")
        else:
            newpath = os.path.normpath(os.path.join(path, sys.argv[2]))
        if os.path.exists(newpath):
            path = newpath
        else:
            output = f"cd: {sys.argv[2]}: No such file or directory"
    else:
        command = sys.argv[1:]
        try:
            process = subprocess.Popen(command, cwd=path, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            (stdout, stderr) = process.communicate(timeout=60)
            output = stdout.decode("utf-8") + stderr.decode("utf-8")
        except subprocess.TimeoutExpired:
            process.kill()
            (stdout, stderr) = process.communicate()
            output = stdout.decode("utf-8") + stderr.decode("utf-8")
        except OSError:
            output = f"{sys.argv[1]}: Command not found"

        
print(json.dumps({"path": path, "output": output}))